# Generated by Django 4.2.1 on 2023-05-16 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Nome Perfil')),
            ],
        ),
        migrations.CreateModel(
            name='ProfilePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.permission')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.profile')),
            ],
            options={
                'unique_together': {('profile', 'permission')},
            },
        ),
        migrations.DeleteModel(
            name='CustomGroup',
        ),
        migrations.AddField(
            model_name='profile',
            name='permissions',
            field=models.ManyToManyField(through='user.ProfilePermission', to='auth.permission'),
        ),
        migrations.AddField(
            model_name='user',
            name='profile',
            field=models.ManyToManyField(to='user.profile', verbose_name='Níveis'),
        ),
    ]
