# Generated by Django 4.2.1 on 2023-05-16 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_profile_profilepermission_delete_customgroup_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='profile',
            new_name='profiles',
        ),
    ]
